from __future__ import annotations

from typing import Any

from aimilivpn.system.web_runtime import WebRuntimeWiring


def build_web_runtime_wiring(runtime: Any) -> WebRuntimeWiring:
    return WebRuntimeWiring(
        region_repository=runtime.region_repository,
        read_regions=runtime.read_regions,
        read_nodes=runtime.read_nodes,
        region_from_payload=runtime.region_from_payload,
        quality_provider_status=runtime.quality_provider_status,
        latest_quality_for_node=runtime.latest_quality_for_node,
        latest_quality_map=runtime.latest_quality_map,
        test_node_by_id=runtime.test_node_by_id,
        check_quality_ip=runtime.check_quality_ip,
        check_quality_region=runtime.check_quality_region,
        bounded_int=runtime.bounded_int,
        scamalytics_errors=runtime.scamalytics_errors,
        write_nodes=runtime.write_nodes,
        filter_nodes_by_region=runtime.filter_nodes_by_region,
        get_state=runtime.get_state,
        set_state=runtime.set_state,
        get_active_node_id=runtime.get_active_node_id,
        get_last_active_ping_time=runtime.get_last_active_ping_time,
        set_last_active_ping_time=runtime.set_last_active_ping_time,
        get_last_active_latency=runtime.get_last_active_latency,
        set_last_active_latency=runtime.set_last_active_latency,
        now=runtime.now,
        ping_latency_ms=runtime.ping_latency_ms,
        parse_int=runtime.parse_int,
        start_daemon_thread=runtime.start_daemon_thread,
        test_multiple_nodes=runtime.test_multiple_nodes,
        connect_node=runtime.connect_node,
        stop_active_openvpn=runtime.stop_active_openvpn,
        load_ui_config=runtime.load_ui_config,
        save_ui_config_unlocked=runtime.save_ui_config_unlocked,
        maintain_valid_nodes=runtime.maintain_valid_nodes,
        maintenance_running=runtime.maintenance_running,
        start_maintenance=runtime.start_maintenance,
        validate_routing_region_target=runtime.validate_routing_region_target,
        verify_password=runtime.verify_password,
        verify_username=runtime.verify_username,
        generate_session_token=runtime.generate_session_token,
        check_proxy_health=runtime.check_proxy_health,
        ui_host=runtime.ui_host,
        ui_port=runtime.ui_port,
        proxy_host=runtime.proxy_host,
        proxy_port=runtime.proxy_port,
        active_openvpn_running=runtime.active_openvpn_running,
        is_linux=runtime.is_linux,
        tun_dev=runtime.tun_dev,
        server_start_time=runtime.server_start_time,
        last_collector_heartbeat=runtime.last_collector_heartbeat,
        last_checker_heartbeat=runtime.last_checker_heartbeat,
        last_pinger_heartbeat=runtime.last_pinger_heartbeat,
        check_interval_seconds=runtime.check_interval_seconds,
        login_html_fallback=runtime.login_html_fallback,
        index_html_fallback=runtime.index_html_fallback,
        active_sessions=runtime.active_sessions,
        lock=runtime.lock,
        data_dir=runtime.data_dir,
        console_token=runtime.console_token,
        diagnose_local_obstructions=runtime.diagnose_local_obstructions,
        start_thread=runtime.start_thread,
        sleep=runtime.sleep,
        exit_process=runtime.exit_process,
        print_line=runtime.print_line,
    )
