from __future__ import annotations

from collections.abc import MutableMapping
from typing import Any


RUNTIME_CONTEXT_EXPORTS = (
    "install_ipv4_preferred_getaddrinfo",
    "vpn_utils",
    "redact_log_message",
    "QualityResult",
    "ScamalyticsError",
    "proxy_server",
    "console_token",
    "diagnose_with_host_keyword",
    "exit_process",
    "is_linux",
    "module_log_writer",
    "print_line",
    "set_stderr",
    "set_stdout",
    "bounded_int",
    "parse_int",
    "safe_name",
    "default_index_html",
    "default_login_html",
    "start_daemon_threads",
    "wait_for_gateway",
    "quality_to_dict",
    "region_to_dict",
    "serve_web_forever",
    "time",
)


CONTEXT_EXPORTS = (
    ("MANAGER_ENVIRONMENT", "environment"),
    ("ROOT_DIR", "root_dir"),
    ("MANAGER_CONFIG", "config"),
    ("API_URL", "api_url"),
    ("FETCH_INTERVAL_SECONDS", "fetch_interval_seconds"),
    ("CHECK_INTERVAL_SECONDS", "check_interval_seconds"),
    ("TARGET_VALID_NODES", "target_valid_nodes"),
    ("MAX_SCAN_ROWS", "max_scan_rows"),
    ("OPENVPN_TEST_TIMEOUT_SECONDS", "openvpn_test_timeout_seconds"),
    ("OPENVPN_MAINTENANCE_TEST_TIMEOUT_SECONDS", "openvpn_maintenance_test_timeout_seconds"),
    ("NODE_TEST_WORKERS", "node_test_workers"),
    ("MAX_MAINTENANCE_TEST_NODES", "max_maintenance_test_nodes"),
    ("NODE_RETEST_INTERVAL_SECONDS", "node_retest_interval_seconds"),
    ("OPENVPN_CMD", "openvpn_cmd"),
    ("OPENVPN_AUTH_USER", "openvpn_auth_user"),
    ("OPENVPN_AUTH_PASS", "openvpn_auth_pass"),
    ("LOCAL_PROXY_HOST", "local_proxy_host"),
    ("LOCAL_PROXY_PORT", "local_proxy_port"),
    ("UI_HOST", "ui_host"),
    ("UI_PORT", "ui_port"),
    ("INVALID_BACKOFF_SECONDS", "invalid_backoff_seconds"),
    ("INSTANCE_ID", "instance_id"),
    ("TUN_DEV", "tun_dev"),
    ("POLICY_TABLE", "policy_table"),
    ("ALLOWED_COUNTRIES", "allowed_countries"),
    ("EXCLUDE_DATACENTER", "exclude_datacenter"),
    ("ALLOW_INSECURE_FETCH", "allow_insecure_fetch"),
    ("STORAGE_BACKEND", "storage_backend"),
    ("SQLITE_DB_PATH", "sqlite_db_path"),
    ("RUNTIME_PATHS", "runtime_paths"),
    ("DATA_DIR", "data_dir"),
    ("CONFIG_DIR", "config_dir"),
    ("NODES_FILE", "nodes_file"),
    ("STATE_FILE", "state_file"),
    ("AUTH_FILE", "auth_file"),
    ("UPSTREAM_PROXY_AUTH_FILE", "upstream_proxy_auth_file_path"),
    ("BLACKLIST_FILE", "blacklist_file"),
    ("REGIONS_FILE", "regions_file"),
    ("QUALITY_RESULTS_FILE", "quality_results_file"),
    ("SETTINGS_FILE", "settings_file"),
    ("REPOSITORIES", "repositories"),
    ("NODE_REPOSITORY", "node_repository"),
    ("REGION_REPOSITORY", "region_repository"),
    ("QUALITY_REPOSITORY", "quality_repository"),
    ("SETTINGS_REPOSITORY", "settings_repository"),
    ("SHARED_STATE", "shared_state"),
    ("UI_ENDPOINTS", "ui_endpoints"),
    ("manager_repository_runtime", "manager_repository_runtime"),
    ("repository_facade", "repository_facade"),
    ("read_nodes", "read_nodes"),
    ("write_nodes", "write_nodes"),
    ("read_regions", "read_regions"),
    ("region_from_payload", "region_from_payload"),
    ("filter_nodes_by_region", "filter_nodes_by_region"),
    ("region_target_id", "region_target_id"),
    ("get_region_routing_target", "get_region_routing_target"),
    ("routing_target_label", "routing_target_label"),
    ("node_matches_country_target", "node_matches_country_target"),
    ("node_matches_routing_region", "node_matches_routing_region"),
    ("filter_nodes_by_routing_region", "filter_nodes_by_routing_region"),
    ("validate_routing_region_target", "validate_routing_region_target"),
    ("manager_quality_runtime", "manager_quality_runtime"),
    ("get_scamalytics_provider", "get_scamalytics_provider"),
    ("latest_quality_for_node", "latest_quality_for_node"),
    ("latest_quality_map", "latest_quality_map"),
    ("check_quality_region", "check_quality_region"),
    ("quality_provider_status", "quality_provider_status"),
    ("lock", "lock"),
    ("maintenance_lock", "maintenance_lock"),
    ("mutable_state", "mutable_state"),
    ("active_sessions", "active_sessions"),
    ("manager_auth_runtime", "manager_auth_runtime"),
    ("get_session_token", "get_session_token"),
    ("manager_ui_runtime", "manager_ui_runtime"),
    ("generate_random_password", "generate_random_password"),
    ("generate_random_username", "generate_random_username"),
    ("ui_config_store", "ui_config_store"),
    ("load_ui_config", "load_ui_config"),
    ("save_ui_config", "save_ui_config"),
    ("manager_runtime_state", "manager_runtime_state"),
    ("write_json", "write_json"),
    ("read_json", "read_json"),
    ("runtime_state_store", "runtime_state_store"),
    ("set_state", "set_state"),
    ("get_state", "get_state"),
    ("manager_runtime_files", "manager_runtime_files"),
    ("ensure_dirs", "ensure_dirs"),
    ("upstream_proxy_auth_file", "upstream_proxy_auth_file"),
    ("write_ovpn_config", "write_ovpn_config"),
    ("manager_thread_runtime", "manager_thread_runtime"),
    ("run_with_lock", "run_with_lock"),
    ("try_acquire_maintenance_lock", "try_acquire_maintenance_lock"),
    ("release_maintenance_lock", "release_maintenance_lock"),
    ("start_background_thread", "start_background_thread"),
    ("start_daemon_thread", "start_daemon_thread"),
    ("start_maintenance_thread", "start_maintenance_thread"),
    ("manager_node_view_runtime", "manager_node_view_runtime"),
    ("node_matches_allowed_countries", "node_matches_allowed_countries"),
    ("context_active_node_id", "context_active_node_id"),
    ("sort_all_nodes", "sort_all_nodes"),
    ("manager_proxy_health_runtime", "manager_proxy_health_runtime"),
    ("check_proxy_health", "check_proxy_health"),
    ("json_log_runtime", "json_log_runtime"),
    ("json_log_writer", "json_log_writer"),
    ("cleanup_old_logs", "cleanup_old_logs"),
    ("log_to_json", "log_to_json"),
    ("manager_fetch_runtime", "manager_fetch_runtime"),
    ("vpngate_fetch_facade", "vpngate_fetch_facade"),
    ("fetch_api_text_via_proxy", "fetch_api_text_via_proxy"),
    ("fetch_api_text", "fetch_api_text"),
    ("blacklist_store", "blacklist_store"),
    ("load_blacklist", "load_blacklist"),
    ("mark_blacklisted", "mark_blacklisted"),
    ("fetch_candidates", "fetch_candidates"),
    ("cached_nodes", "cached_nodes"),
    ("manager_connection_runtime", "manager_connection_runtime"),
    ("clear_active_connection_state", "clear_active_connection_state"),
    ("get_is_connecting", "get_is_connecting"),
    ("set_is_connecting", "set_is_connecting"),
    ("get_active_openvpn_node_id", "get_active_openvpn_node_id"),
    ("set_active_openvpn_node_id", "set_active_openvpn_node_id"),
    ("set_active_openvpn_connection", "set_active_openvpn_connection"),
    ("connection_runtime_facade", "connection_runtime_facade"),
    ("connection_orchestrator", "connection_orchestrator"),
    ("stop_active_openvpn", "stop_active_openvpn"),
    ("active_openvpn_running", "active_openvpn_running"),
    ("get_last_active_ping_time", "get_last_active_ping_time"),
    ("set_last_active_ping_time", "set_last_active_ping_time"),
    ("get_last_active_latency", "get_last_active_latency"),
    ("set_last_active_latency", "set_last_active_latency"),
    ("manager_monitoring_runtime", "manager_monitoring_runtime"),
    ("monitoring_runtime", "monitoring_runtime"),
    ("set_collector_heartbeat", "set_collector_heartbeat"),
    ("set_checker_heartbeat", "set_checker_heartbeat"),
    ("set_pinger_heartbeat", "set_pinger_heartbeat"),
    ("collector_loop", "collector_loop"),
    ("background_proxy_checker", "background_proxy_checker"),
    ("active_node_pinger", "active_node_pinger"),
    ("manager_web_runtime", "manager_web_runtime"),
    ("web_runtime_wiring", "web_runtime_wiring"),
    ("clear_active_sessions", "clear_active_sessions"),
    ("schedule_server_restart", "schedule_server_restart"),
    ("save_ui_config_locked", "save_ui_config_locked"),
    ("add_active_session", "add_active_session"),
    ("remove_active_session", "remove_active_session"),
    ("proxy_gateway_status", "proxy_gateway_status"),
    ("read_api_log_entries", "read_api_log_entries"),
    ("route_context_factory", "route_context_factory"),
    ("web_server_runtime", "web_server_runtime"),
    ("manager_openvpn_runtime", "manager_openvpn_runtime"),
    ("openvpn_runtime_facade", "openvpn_runtime_facade"),
    ("policy_routing_facade", "policy_routing_facade"),
    ("split_openvpn_command", "split_openvpn_command"),
    ("get_openvpn_version", "get_openvpn_version"),
    ("stop_process", "stop_process"),
    ("kill_existing_openvpn_processes", "kill_existing_openvpn_processes"),
    ("setup_policy_routing", "setup_policy_routing"),
    ("cleanup_policy_routing", "cleanup_policy_routing"),
    ("manager_service_runtime", "manager_service_runtime"),
    ("manager_entry_runtime", "manager_entry_runtime"),
    ("service_runtime", "service_runtime"),
    ("manager_node_probe_runtime", "manager_node_probe_runtime"),
    ("node_probe_runtime", "node_probe_runtime"),
    ("test_node_by_id", "test_node_by_id"),
    ("select_maintenance_test_nodes", "select_maintenance_test_nodes"),
)


def export_context_globals(
    namespace: MutableMapping[str, Any],
    context: Any,
    runtime_module: Any,
) -> None:
    for name in RUNTIME_CONTEXT_EXPORTS:
        namespace[name] = getattr(runtime_module, name)
    for export_name, context_attr in CONTEXT_EXPORTS:
        namespace[export_name] = getattr(context, context_attr)
